---
title: Lesebühne Text Genuß & Schnaps + Vorträge
timezone: Europe/Berlin
collections:
  galerie:
    title: Galerie
    output: true
  lesende:
    title: Lesende
    output: true
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
  values:
    layout: default
description: Die Lesebühne Text Genuß & Schnaps + Vorträge ist eine unregelmäßig und
  an wechselnden Orten stattfindende Lesebühne in Hannover. Wir sind Mitglied im Netzwerk
  Unabhängige Lesereihen.
email: lesebuehnehannover@gmail.com
facebook: https://www.facebook.com/lesebuehnetextgenuss/
instagram: https://www.instagram.com/lesebuehnetextgenuss/
podcast: https://anchor.fm/lesebhne-text-genu--schnaps--vortrge
announcement: 'Nächste Lesebühne: 20.10.'
announcement_link: https://lesebuehnetextgenuss.de/2023/07/02/open-call.html
sass:
  sass_dir: _sass
  style: compressed
plugins:
- jekyll-responsive-image
responsive_image:
  template: _includes/responsive_image.html
  default_quality: 80
  sizes:
  - width: 160
    quality: 60
  - width: 250
    quality: 70
  - width: 375
    quality: 70
  - width: 470
    quality: 70
  - width: 650
    quality: 75
  - width: 820
  strip: true
  cache: true
  extra_images:
  - uploads/*/*/*/*.{jpeg,jpg}
