title: |
        Lesebühne 
        Text Genuß & 
        Schnaps + Vorträge
description: >-
  Lorem ipsum dolor sit amet, consectetur adipiscing elit. 
  Vivamus non lacus eget lacus commodo iaculis. 
  Quisque lobortis felis et bibendum egestas. 
email: lesebuehnehannover@gmail.com
facebook: https://www.facebook.com/lesebuehnetextgenuss/
instagram: https://www.instagram.com/lesebuehnetextgenuss/
announcement: |
  Nächste Lesung am:
  27.6.20 um 10:30
announcement_link: 2020/06/13/Artbeerbowlothek.html

collections:
  lesende: 
    output: true
  pages: 
    output: true
  galerie: 
    output: true

sass:
        sass_dir: _sass
        style: compressed
defaults:
  -
    scope:
      path: "" 
    values:
      layout: "default"

timezone: Europe/Berlin
