---
title: "Lesebühne \nText Genuß & \nSchnaps + Vorträge\n"
timezone: Europe/Berlin
collections:
  galerie:
    title: Galerie
    output: true
  lesende:
    title: Lesende
    output: true
  pages:
    title: Pages
    output: true
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
  values:
    layout: default
description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.  Vivamus non
  lacus eget lacus commodo iaculis.  Quisque lobortis felis et bibendum egestas. '
email: lesebuehnehannover@gmail.com
facebook: https://www.facebook.com/lesebuehnetextgenuss/
instagram: https://www.instagram.com/lesebuehnetextgenuss/
announcement: |
  Nächste Lesung am:
  27.6.20 um 10:30
announcement_link: 2020/06/13/Artbeerbowlothek.html
sass:
  sass_dir: _sass
  style: compressed
plugins:
- jekyll-responsive-image
responsive_image:
  template: _includes/responsive_image.html
  default_quality: 80
  sizes:
  - width: 480
    quality: 80
  - width: 800
  - width: 1400
    quality: 90
  strip: true
  cache: true
  extra_images:
  - uploads/*/*/*/*.{jpeg,jpg}
prose:
  siteurl: http://lb.merlinschumacher.de
  media: fotos
  metadata:
    _posts:
    - name: layout
      field:
        element: hidden
        value: default
    - name: title
      field:
        element: text
        label: Title
        value: ''
    _pages:
    - name: layout
      field:
        element: hidden
        value: page
    - name: title
      field:
        element: text
        label: Title
        value: ''
    - name: permalink
      field:
        element: text
        label: Permalink
        value: ''
