---
title: Lesebühne Text Genuß & Schnaps + Vorträge
timezone: Europe/Berlin
collections:
  galerie:
    title: Galerie
    output: true
  lesende:
    title: Lesende
    output: true
  posts:
    title: Posts
    output: true
    permalink: /:collection/:name:output_ext
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
  values:
    layout: default
description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.  Vivamus non
  lacus eget lacus commodo iaculis.  Quisque lobortis felis et bibendum egestas. '
email: lesebuehnehannover@gmail.com
facebook: https://www.facebook.com/lesebuehnetextgenuss/
instagram: https://www.instagram.com/lesebuehnetextgenuss/
announcement: |
  Nächste Lesung am:
  27.6.20 um 10:30
announcement_link: posts/Artbeerbowlothek.html
sass:
  sass_dir: _sass
  style: compressed
plugins:
- jekyll-responsive-image
responsive_image:
  template: _includes/responsive_image.html
  default_quality: 80
  sizes:
  - width: 480
    quality: 80
  - width: 800
  - width: 1400
    quality: 90
  strip: true
  cache: true
  extra_images:
  - uploads/*/*/*/*.{jpeg,jpg}
